### ISSUE TITLE
Application crash in iOS 8 sdk.

### ISSUE THREAD

**Issue by ramkrishnazingma** [mohammedDehairy/MDImageCroper#1]
Hi Mohammed,

Thanks for sharing your application, but it crashed while click on the cat image.

Please find the below crash log.

Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextFillRects: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSetShouldAntialias: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSetAllowsAntialiasing: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSetInterpolationQuality: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextBeginPath: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextAddPath: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: clip: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSaveGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextSetCompositeOperation: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextFillRects: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGContextRestoreGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Feb 17 12:22:55 Ramkrishnas-Mac-mini.local MDImageCroper Demo[719] <Error>: CGImageMaskCreate: invalid image size: 0 x 0.

Please let me know if you need any more information for the same.

**Comment by mohammedDehairy** [comment]
you clicked the cat photo twice so the first one cropped the cat image to a size equal CGSizeZero , then the second click tried to crop a photo with a zero size .

i fixed it by checking if the image size is equal to CGSizeZero .

as for the other warnings , those are common bugs generated under iOS 7 and 8 , but the app will function normally , i am afraid i can't help them, may be you'll have more luck fixing them.
